name: Bug report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report!
  - type: input
    id: dart_version
    attributes:
      label: Dart version
      description: Dart SDK version you are using.
      placeholder: "3.8.1"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package version
      description: ThemeTailor generator version you are using.
      placeholder: "3.1.0"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Actual behaviour
      description: "What did you observe that was not expected?"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: "What did you expect to happen?"
    validations:
      required: true
